[package]
name = "oxide-dev-tools-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "CLI tool for oxide-dev-tools"

[[bin]]
name = "oxide"
path = "src/main.rs"

[dependencies]
oxide-dev-tools-core = { path = "../oxide-dev-tools-core", version = "0.1.0" }
clap = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
